# Generated by Django 5.0 on 2024-01-01 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_productline_product_productimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimage',
            name='image',
        ),
        migrations.AddField(
            model_name='productimage',
            name='url',
            field=models.ImageField(default='test.jpg', upload_to=''),
        ),
    ]
